server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    # URL Interna completa con puerto 5432
    url: jdbc:postgresql://dpg-d4qafl15pdvs738ktpa0-a:5432/portfolio_db_b26b

    # Credenciales directas
    username: portfolio_db_b26b_user
    password: Lajkj0L1hgYO3fMDsSRUNEUJhv23L42e

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
