server:
  port: 8080

spring:
  # Configuraciones de la Base de Datos
  datasource:
    # Estas variables serán inyectadas desde docker-compose.yml (local) o el panel de Render (cloud)
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  # Configuración de JPA (Hibernate)
  jpa:
    hibernate:
      # 'update' creará o modificará las tablas automáticamente
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        # Dialecto para PostgreSQL
        dialect: org.hibernate.dialect.PostgreSQLDialect