server:
  port: 8080

spring:
  # Configuraciones de la Base de Datos
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  # Configuración de JPA (Hibernate)
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    # properties:                   <-- Comenta o borra desde aquí
    #   hibernate:
    #     dialect: org.hibernate.dialect.PostgreSQLDialect
